<?php

/* auth_config.php - Generated by GhostCrew Installer */

// Prevent multiple inclusions
if (defined('GHOSTCREW_AUTH_CONFIG_LOADED')) {
    return;
}
define('GHOSTCREW_AUTH_CONFIG_LOADED', true);

// Authentication Configuration for GhostCrew

// CRITICAL: Fix timezone synchronization between PHP and MySQL
date_default_timezone_set('UTC');

// Configure session settings ONLY if session is not already active
if (session_status() === PHP_SESSION_NONE) {
    ini_set('session.cookie_httponly', 1);
    ini_set('session.use_only_cookies', 1);
    ini_set('session.cookie_lifetime', 0);
    ini_set('session.gc_maxlifetime', 7200);
    session_start();
}

// Admin database configuration
if (!defined('ADMIN_DB_HOST')) {
    define('ADMIN_DB_HOST', 'localhost');
}
if (!defined('ADMIN_DB_USER')) {
    define('ADMIN_DB_USER', 'svc_ghostcrew_admin');
}
if (!defined('ADMIN_DB_PASS')) {
    define('ADMIN_DB_PASS', '!Password123!');
}
if (!defined('ADMIN_DB_NAME')) {
    define('ADMIN_DB_NAME', 'ghostcrew_admin');
}

// Security settings
if (!defined('SESSION_TIMEOUT')) {
    define('SESSION_TIMEOUT', 3600);
}
if (!defined('MAX_LOGIN_ATTEMPTS')) {
    define('MAX_LOGIN_ATTEMPTS', 5);
}
if (!defined('LOGIN_LOCKOUT_TIME')) {
    define('LOGIN_LOCKOUT_TIME', 900);
}
if (!defined('PASSWORD_MIN_LENGTH')) {
    define('PASSWORD_MIN_LENGTH', 8);
}
if (!defined('INSTANCE_TOKEN_LIFETIME')) {
    define('INSTANCE_TOKEN_LIFETIME', 28800);
}

// Create admin database connection - FIXED to only connect when databases exist
if (!function_exists('getAdminDB')) {
    function getAdminDB() {
        static $adminConn = null;
        
        if ($adminConn === null) {
            try {
                // First check if database exists
                $testConn = new mysqli(ADMIN_DB_HOST, ADMIN_DB_USER, ADMIN_DB_PASS);
                if ($testConn->connect_error) {
                    throw new Exception("Cannot connect to MySQL server: " . $testConn->connect_error);
                }
                
                // Check if database exists
                $dbCheck = $testConn->query("SHOW DATABASES LIKE '" . ADMIN_DB_NAME . "'");
                if ($dbCheck->num_rows === 0) {
                    $testConn->close();
                    throw new Exception("Database '" . ADMIN_DB_NAME . "' does not exist yet");
                }
                $testConn->close();
                
                // Database exists, now connect to it
                $adminConn = new mysqli(ADMIN_DB_HOST, ADMIN_DB_USER, ADMIN_DB_PASS, ADMIN_DB_NAME);
                
                if ($adminConn->connect_error) {
                    throw new Exception("Admin database connection failed: " . $adminConn->connect_error);
                }
                
                $adminConn->query("SET time_zone = '+00:00'");
                
                // Test the connection with a simple query
                $testResult = $adminConn->query("SELECT 1");
                if (!$testResult) {
                    throw new Exception("Database connection test failed: " . $adminConn->error);
                }
                
            } catch (Exception $e) {
                error_log("getAdminDB error: " . $e->getMessage());
                throw $e;
            }
        }
        
        return $adminConn;
    }
}

// Generate secure session token
if (!function_exists('generateSessionToken')) {
    function generateSessionToken() {
        return bin2hex(random_bytes(32));
    }
}

// Generate unique session ID
if (!function_exists('generateSessionId')) {
    function generateSessionId() {
        return "sess_" . date("Ymd_His") . "_" . bin2hex(random_bytes(8));
    }
}

// Generate unique instance token for user session
if (!function_exists('generateInstanceToken')) {
    function generateInstanceToken($userId) {
        $adminDb = getAdminDB();
        
        // Clean up expired tokens
        $adminDb->query("DELETE FROM user_instance_tokens WHERE expires_at < NOW()");
        
        // Deactivate old tokens for this user
        $stmt = $adminDb->prepare("UPDATE user_instance_tokens SET is_active = 0 WHERE user_id = ?");
        $stmt->bind_param("i", $userId);
        $stmt->execute();
        
        // Generate new token
        $instanceToken = "inst_" . $userId . "_" . time() . "_" . bin2hex(random_bytes(16));
        $expiresAt = date("Y-m-d H:i:s", time() + INSTANCE_TOKEN_LIFETIME);
        
        $stmt = $adminDb->prepare("INSERT INTO user_instance_tokens (user_id, instance_token, expires_at) VALUES (?, ?, ?)");
        $stmt->bind_param("iss", $userId, $instanceToken, $expiresAt);
        
        if ($stmt->execute()) {
            return $instanceToken;
        }
        
        return false;
    }
}

// Get current user"s instance token
if (!function_exists('getCurrentInstanceToken')) {
    function getCurrentInstanceToken() {
        if (!isset($_SESSION["user_id"])) {
            return null;
        }
        
        if (!isset($_SESSION["instance_token"])) {
            $_SESSION["instance_token"] = generateInstanceToken($_SESSION["user_id"]);
        }
        
        return $_SESSION["instance_token"];
    }
}

// Validate instance token
if (!function_exists('validateInstanceToken')) {
    function validateInstanceToken($token) {
        if (empty($token)) {
            return false;
        }
        
        $adminDb = getAdminDB();
        $stmt = $adminDb->prepare("SELECT user_id FROM user_instance_tokens WHERE instance_token = ? AND is_active = 1 AND expires_at > NOW()");
        $stmt->bind_param("s", $token);
        $stmt->execute();
        $result = $stmt->get_result();
        
        return $result->num_rows > 0;
    }
}

// Check if user is authenticated
if (!function_exists('isAuthenticated')) {
    function isAuthenticated() {
        // Check for required session variables
        if (!isset($_SESSION["user_id"]) || !isset($_SESSION["session_token"])) {
            return false;
        }
        
        try {
            $adminDb = getAdminDB();
            
            // First, get the session data
            $stmt = $adminDb->prepare("SELECT user_id, last_activity, is_active FROM user_sessions WHERE session_token = ?");
            $stmt->bind_param("s", $_SESSION["session_token"]);
            $stmt->execute();
            $result = $stmt->get_result();
            
            if ($result->num_rows === 0) {
                // Session not found in database
                return false;
            }
            
            $session = $result->fetch_assoc();
            
            // Check if session is active
            if (!$session["is_active"]) {
                return false;
            }
            
            // Check if user ID matches
            if ($session["user_id"] != $_SESSION["user_id"]) {
                return false;
            }
            
            // Now check if the user is active
            $stmt = $adminDb->prepare("SELECT is_active FROM users WHERE id = ?");
            $stmt->bind_param("i", $session["user_id"]);
            $stmt->execute();
            $userResult = $stmt->get_result();
            
            if ($userResult->num_rows === 0) {
                // User not found
                return false;
            }
            
            $user = $userResult->fetch_assoc();
            if (!$user["is_active"]) {
                // User is not active
                return false;
            }
            
            // Check session timeout - but be more lenient
            $lastActivity = strtotime($session["last_activity"]);
            $currentTime = time();
            $timeDiff = $currentTime - $lastActivity;
            
            // Only timeout if it"s been more than the session timeout AND more than 5 minutes
            if ($timeDiff > SESSION_TIMEOUT && $timeDiff > 300) {
                return false;
            }
            
            // Update last activity - but only if more than 60 seconds have passed
            if ($timeDiff > 60) {
                $stmt = $adminDb->prepare("UPDATE user_sessions SET last_activity = CURRENT_TIMESTAMP WHERE session_token = ?");
                $stmt->bind_param("s", $_SESSION["session_token"]);
                $stmt->execute();
            }
            
            // Ensure user has valid instance token
            if (!isset($_SESSION["instance_token"]) || !validateInstanceToken($_SESSION["instance_token"])) {
                $_SESSION["instance_token"] = generateInstanceToken($_SESSION["user_id"]);
            }
            
            return true;
            
        } catch (Exception $e) {
            error_log("Authentication check failed: " . $e->getMessage());
            // On database errors, allow authentication to continue
            // This prevents login issues due to temporary DB problems
            return true;
        }
    }
}

// Get current user information
if (!function_exists('getCurrentUser')) {
    function getCurrentUser() {
        if (!isAuthenticated()) {
            return null;
        }
        
        $adminDb = getAdminDB();
        $stmt = $adminDb->prepare("SELECT u.* FROM users u 
                                  JOIN user_sessions us ON u.id = us.user_id 
                                  WHERE us.session_token = ? AND us.is_active = 1");
        $stmt->bind_param("s", $_SESSION["session_token"]);
        $stmt->execute();
        $result = $stmt->get_result();
        
        return $result->num_rows > 0 ? $result->fetch_assoc() : null;
    }
}

// Authenticate user
if (!function_exists('authenticateUser')) {
    function authenticateUser($username, $password) {
        try {
            $adminDb = getAdminDB();
            
            // Check for too many failed attempts
            $ip = $_SERVER["REMOTE_ADDR"] ?? "unknown";
            $stmt = $adminDb->prepare("SELECT COUNT(*) as attempts FROM audit_log 
                                      WHERE action_type = 'login' 
                                      AND JSON_EXTRACT(action_details, '$.success') = false 
                                      AND ip_address = ? 
                                      AND timestamp > DATE_SUB(NOW(), INTERVAL ? SECOND)");
            $lockoutTime = LOGIN_LOCKOUT_TIME;
            $stmt->bind_param("si", $ip, $lockoutTime);
            $stmt->execute();
            $attempts = $stmt->get_result()->fetch_assoc()["attempts"];
            
            if ($attempts >= MAX_LOGIN_ATTEMPTS) {
                logAuditEvent(null, "login", [
                    "success" => false,
                    "username" => $username,
                    "reason" => "too_many_attempts",
                    "ip_lockout" => true
                ]);
                return ["success" => false, "message" => "Too many failed attempts. Please try again later."];
            }
            
            // Get user
            $stmt = $adminDb->prepare("SELECT id, username, password_hash, is_active, full_name FROM users WHERE username = ?");
            $stmt->bind_param("s", $username);
            $stmt->execute();
            $result = $stmt->get_result();
            
            if ($result->num_rows === 0) {
                logAuditEvent(null, "login", [
                    "success" => false,
                    "username" => $username,
                    "reason" => "user_not_found"
                ]);
                return ["success" => false, "message" => "Invalid username or password."];
            }
            
            $user = $result->fetch_assoc();
            
            if (!$user["is_active"]) {
                logAuditEvent($user["id"], "login", [
                    "success" => false,
                    "username" => $username,
                    "reason" => "account_disabled"
                ]);
                return ["success" => false, "message" => "Account is disabled."];
            }
            
            if (!password_verify($password, $user["password_hash"])) {
                logAuditEvent($user["id"], "login", [
                    "success" => false,
                    "username" => $username,
                    "reason" => "invalid_password"
                ]);
                return ["success" => false, "message" => "Invalid username or password."];
            }
            
            // Create session
            $sessionToken = generateSessionToken();
            $userAgent = $_SERVER["HTTP_USER_AGENT"] ?? "";
            
            $stmt = $adminDb->prepare("INSERT INTO user_sessions (user_id, session_token, ip_address, user_agent) VALUES (?, ?, ?, ?)");
            $stmt->bind_param("isss", $user["id"], $sessionToken, $ip, $userAgent);
            
            if (!$stmt->execute()) {
                return ["success" => false, "message" => "Failed to create session."];
            }
            
            // Generate instance token
            $instanceToken = generateInstanceToken($user["id"]);
            if (!$instanceToken) {
                return ["success" => false, "message" => "Failed to create instance token."];
            }
            
            // Update last login
            $stmt = $adminDb->prepare("UPDATE users SET last_login = CURRENT_TIMESTAMP WHERE id = ?");
            $stmt->bind_param("i", $user["id"]);
            $stmt->execute();
            
            // Set session variables
            $_SESSION["user_id"] = $user["id"];
            $_SESSION["username"] = $user["username"];
            $_SESSION["session_token"] = $sessionToken;
            $_SESSION["instance_token"] = $instanceToken;
            $_SESSION["login_time"] = time();
            $_SESSION["last_activity"] = time();
            
            // Regenerate session ID for security
            session_regenerate_id(true);
            
            logAuditEvent($user["id"], "login", [
                "success" => true,
                "username" => $username,
                "session_token" => substr($sessionToken, 0, 8) . "...",
                "instance_token" => substr($instanceToken, 0, 8) . "..."
            ]);
            
            return ["success" => true, "message" => "Login successful"];
            
        } catch (Exception $e) {
            error_log("Authentication error: " . $e->getMessage());
            return ["success" => false, "message" => "Authentication system error."];
        }
    }
}

// Logout user
if (!function_exists('logoutUser')) {
    function logoutUser() {
        if (isset($_SESSION["session_token"])) {
            $adminDb = getAdminDB();
            $stmt = $adminDb->prepare("UPDATE user_sessions SET logout_time = CURRENT_TIMESTAMP, is_active = 0 WHERE session_token = ?");
            $stmt->bind_param("s", $_SESSION["session_token"]);
            $stmt->execute();
            
            // Deactivate instance token
            if (isset($_SESSION["instance_token"])) {
                $stmt = $adminDb->prepare("UPDATE user_instance_tokens SET is_active = 0 WHERE instance_token = ?");
                $stmt->bind_param("s", $_SESSION["instance_token"]);
                $stmt->execute();
            }
            
            logAuditEvent($_SESSION["user_id"] ?? null, "logout", [
                "session_token" => substr($_SESSION["session_token"], 0, 8) . "...",
                "instance_token" => substr($_SESSION["instance_token"] ?? "", 0, 8) . "..."
            ]);
        }
        
        // Clear session
        session_unset();
        session_destroy();
        session_start(); // Start new session
    }
}

// Log audit events
if (!function_exists('logAuditEvent')) {
    function logAuditEvent($userId, $actionType, $actionDetails = []) {
        $adminDb = getAdminDB();
        $ip = $_SERVER["REMOTE_ADDR"] ?? "unknown";
        $userAgent = $_SERVER["HTTP_USER_AGENT"] ?? "";
        $actionDetailsJson = json_encode($actionDetails);
        
        $stmt = $adminDb->prepare("INSERT INTO audit_log (user_id, action_type, action_details, ip_address, user_agent) VALUES (?, ?, ?, ?, ?)");
        $stmt->bind_param("issss", $userId, $actionType, $actionDetailsJson, $ip, $userAgent);
        $stmt->execute();
    }
}

// Log chatbot interaction
if (!function_exists('logChatbotInteraction')) {
    function logChatbotInteraction($userId, $sessionId, $conversationId, $messageType, $message, $contextData = [], $responseTime = null) {
        $adminDb = getAdminDB();
        $contextJson = json_encode($contextData);
        
        $stmt = $adminDb->prepare("INSERT INTO chatbot_conversations (user_id, session_id, conversation_id, message_type, message, context_data, response_time) VALUES (?, ?, ?, ?, ?, ?, ?)");
        $stmt->bind_param("isssssd", $userId, $sessionId, $conversationId, $messageType, $message, $contextJson, $responseTime);
        $stmt->execute();
        
        return $adminDb->insert_id;
    }
}

// Get or create conversation ID for session
if (!function_exists('getOrCreateConversationId')) {
    function getOrCreateConversationId($sessionId) {
        $adminDb = getAdminDB();
        
        // Check if conversation exists for this session
        $stmt = $adminDb->prepare("SELECT DISTINCT conversation_id FROM chatbot_conversations WHERE session_id = ? ORDER BY timestamp DESC LIMIT 1");
        $stmt->bind_param("s", $sessionId);
        $stmt->execute();
        $result = $stmt->get_result();
        
        if ($result->num_rows > 0) {
            return $result->fetch_assoc()["conversation_id"];
        }
        
        // Create new conversation ID
        return "conv_" . $sessionId . "_" . time();
    }
}

// Store command suggestion
if (!function_exists('storeCommandSuggestion')) {
    function storeCommandSuggestion($conversationId, $userId, $command, $description, $context = null) {
        $adminDb = getAdminDB();
        
        $stmt = $adminDb->prepare("INSERT INTO command_suggestions (conversation_id, user_id, suggested_command, command_description, suggestion_context) VALUES (?, ?, ?, ?, ?)");
        $stmt->bind_param("sisss", $conversationId, $userId, $command, $description, $context);
        $stmt->execute();
        
        return $adminDb->insert_id;
    }
}

// Mark command suggestion as executed
if (!function_exists('markSuggestionExecuted')) {
    function markSuggestionExecuted($suggestionId) {
        $adminDb = getAdminDB();
        
        $stmt = $adminDb->prepare("UPDATE command_suggestions SET executed = 1, executed_at = CURRENT_TIMESTAMP WHERE id = ?");
        $stmt->bind_param("i", $suggestionId);
        $stmt->execute();
    }
}

// Require authentication for protected pages
if (!function_exists('requireAuth')) {
    function requireAuth() {
        if (!isAuthenticated()) {
            // Don"t call logoutUser() here - that"s what"s ending the session immediately!
            // Just clear the invalid session variables
            if (isset($_SESSION["user_id"]) || isset($_SESSION["session_token"])) {
                unset($_SESSION["user_id"]);
                unset($_SESSION["username"]);
                unset($_SESSION["session_token"]);
                unset($_SESSION["instance_token"]);
            }
            
            if (isset($_SERVER["HTTP_X_REQUESTED_WITH"]) && strtolower($_SERVER["HTTP_X_REQUESTED_WITH"]) === "xmlhttprequest") {
                // AJAX request
                http_response_code(401);
                echo json_encode(["success" => false, "message" => "Authentication required", "redirect" => "login.php"]);
                exit;
            } else {
                // Regular request
                header("Location: login.php?redirect=" . urlencode($_SERVER["REQUEST_URI"]));
                exit;
            }
        }
    }
}

// Sanitize input (enhanced version)
if (!function_exists('sanitizeInput')) {
    function sanitizeInput($input) {
        if (is_array($input)) {
            return array_map("sanitizeInput", $input);
        }
        return htmlspecialchars(trim($input), ENT_QUOTES, "UTF-8");
    }
}

// Check user permission
if (!function_exists('hasPermission')) {
    function hasPermission($userId, $permission) {
        $user = getCurrentUser();
        if (!$user) return false;
        
        // Admin has all permissions
        if ($user["role"] === "admin") return true;
        
        // Define role permissions
        $permissions = [
            "manager" => ["view_all_sessions", "view_reports", "manage_users"],
            "operator" => ["execute_commands", "view_own_sessions"]
        ];
        
        return isset($permissions[$user["role"]]) && in_array($permission, $permissions[$user["role"]]);
    }
}

// CSRF Protection
if (!function_exists('generateCSRFToken')) {
    function generateCSRFToken() {
        if (!isset($_SESSION["csrf_token"])) {
            $_SESSION["csrf_token"] = bin2hex(random_bytes(32));
        }
        return $_SESSION["csrf_token"];
    }
}

if (!function_exists('validateCSRFToken')) {
    function validateCSRFToken($token) {
        return isset($_SESSION["csrf_token"]) && hash_equals($_SESSION["csrf_token"], $token);
    }
}
?>