<?php

/* config.php - Generated by GhostCrew Installer */

// Enhanced configuration with session support
//define('DB_HOST', 'awseb-e-xfnrcu3bu7-stack-awsebrdsdatabase-56wwqfaxr67o.cyjo80kgwf8g.us-east-1.rds.amazonaws.com');
//define('DB_USER', 'gcadmin34yVbZL');
//define('DB_PASS', 'Aof^Hy4Z%qgHk}CjXV0):Vy]xpcPJ=+');
//define('DB_NAME', 'terminal_app');
//define('APP_URL', 'http://ghostcrew-env.eba-h33ijmhf.us-east-1.elasticbeanstalk.com');
//define('LOCAL_LISTENER_URL', 'http://ghostcrew-env.eba-h33ijmhf.us-east-1.elasticbeanstalk.com/local');

define('DB_HOST', '192.168.1.171');
define('DB_USER', 'svc_terminal-app');
define('DB_PASS', '!Password123!');
define('DB_NAME', 'terminal_app');

// Application configuration
define('APP_URL', 'http://192.168.1.171/GhostCrew');
define('LOCAL_LISTENER_URL', 'http://192.168.1.171/GhostCrew/local');

date_default_timezone_set('UTC');

// Create database connection
$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Set timezone
$conn->query("SET time_zone = '+00:00'");

// Enhanced sanitize function
function sanitize($input) {
    global $conn;
    if (is_array($input)) {
        return array_map('sanitize', $input);
    }
    return $conn->real_escape_string(htmlspecialchars(trim($input), ENT_QUOTES, 'UTF-8'));
}

// Function to log command execution
function logCommandExecution($hostId, $sessionId, $command, $output = null, $executionTime = null, $status = "completed") {
    global $conn;
    
    $stmt = $conn->prepare("UPDATE command_history SET output = ?, execution_time = ?, status = ?, response_timestamp = CURRENT_TIMESTAMP WHERE host_id = ? AND session_id = ? AND command = ? AND status = 'pending' ORDER BY timestamp DESC LIMIT 1");
    $stmt->bind_param("sdsssss", $output, $executionTime, $status, $hostId, $sessionId, $command);
    $stmt->execute();
    $stmt->close();
}

// Function to update shell session state
function updateShellSession($sessionId, $hostId, $currentDirectory = null, $environmentVars = null) {
    global $conn;
    
    // Check if session exists
    $stmt = $conn->prepare("SELECT id FROM shell_sessions WHERE session_id = ?");
    $stmt->bind_param("s", $sessionId);
    $stmt->execute();
    $result = $stmt->get_result();
    
    if ($result->num_rows > 0) {
        // Update existing session
        $updateFields = ["last_activity = CURRENT_TIMESTAMP"];
        $params = "";
        $values = [];
        
        if ($currentDirectory !== null) {
            $updateFields[] = "current_directory = ?";
            $params .= "s";
            $values[] = $currentDirectory;
        }
        
        if ($environmentVars !== null) {
            $updateFields[] = "environment_vars = ?";
            $params .= "s";
            $values[] = json_encode($environmentVars);
        }
        
        $values[] = $sessionId;
        $params .= "s";
        
        $sql = "UPDATE shell_sessions SET " . implode(", ", $updateFields) . " WHERE session_id = ?";
        $stmt = $conn->prepare($sql);
        if (!empty($params)) {
            $stmt->bind_param($params, ...$values);
        }
        $stmt->execute();
    } else {
        // Create new session
        $envJson = $environmentVars ? json_encode($environmentVars) : null;
        $stmt = $conn->prepare("INSERT INTO shell_sessions (session_id, host_id, current_directory, environment_vars) VALUES (?, ?, ?, ?)");
        $stmt->bind_param("ssss", $sessionId, $hostId, $currentDirectory, $envJson);
        $stmt->execute();
    }
    
    $stmt->close();
}

// Function to get shell session state
function getShellSession($sessionId) {
    global $conn;
    
    $stmt = $conn->prepare("SELECT * FROM shell_sessions WHERE session_id = ? AND is_active = 1");
    $stmt->bind_param("s", $sessionId);
    $stmt->execute();
    $result = $stmt->get_result();
    
    if ($result->num_rows > 0) {
        $session = $result->fetch_assoc();
        if ($session["environment_vars"]) {
            $session["environment_vars"] = json_decode($session["environment_vars"], true);
        }
        return $session;
    }
    
    return null;
}

// Function to end shell session
function endShellSession($sessionId) {
    global $conn;
    
    $stmt = $conn->prepare("UPDATE shell_sessions SET is_active = 0 WHERE session_id = ?");
    $stmt->bind_param("s", $sessionId);
    $stmt->execute();
    $stmt->close();
}

// Function to get host statistics
function getHostStatistics($hostId) {
    global $conn;
    
    $stats = [
        "total_sessions" => 0,
        "total_commands" => 0,
        "active_sessions" => 0,
        "last_activity" => null
    ];
    
    // Get total sessions from admin database if available
    if (function_exists("getAdminDB")) {
        try {
            $adminDb = getAdminDB();
            $stmt = $adminDb->prepare("SELECT COUNT(*) as count FROM remote_sessions WHERE host_id = ?");
            $stmt->bind_param("s", $hostId);
            $stmt->execute();
            $result = $stmt->get_result();
            if ($result->num_rows > 0) {
                $stats["total_sessions"] = $result->fetch_assoc()["count"];
            }
            
            $stmt = $adminDb->prepare("SELECT COUNT(*) as count FROM remote_sessions WHERE host_id = ? AND status = 'active'");
            $stmt->bind_param("s", $hostId);
            $stmt->execute();
            $result = $stmt->get_result();
            if ($result->num_rows > 0) {
                $stats["active_sessions"] = $result->fetch_assoc()["count"];
            }
        } catch (Exception $e) {
            // Admin DB not available, use local data
        }
    }
    
    // Get command count
    $stmt = $conn->prepare("SELECT COUNT(*) as count FROM command_history WHERE host_id = ?");
    $stmt->bind_param("s", $hostId);
    $stmt->execute();
    $result = $stmt->get_result();
    if ($result->num_rows > 0) {
        $stats["total_commands"] = $result->fetch_assoc()["count"];
    }
    
    // Get last activity
    $stmt = $conn->prepare("SELECT MAX(timestamp) as last_activity FROM command_history WHERE host_id = ?");
    $stmt->bind_param("s", $hostId);
    $stmt->execute();
    $result = $stmt->get_result();
    if ($result->num_rows > 0) {
        $stats["last_activity"] = $result->fetch_assoc()["last_activity"];
    }
    
    return $stats;
}

// Function to clean up old data (should be called periodically)
function cleanupOldData($daysToKeep = 30) {
    global $conn;
    
    // Clean up old command history
    $stmt = $conn->prepare("DELETE FROM command_history WHERE timestamp < DATE_SUB(NOW(), INTERVAL ? DAY)");
    $stmt->bind_param("i", $daysToKeep);
    $stmt->execute();
    $deleted = $stmt->affected_rows;
    $stmt->close();
    
    // Clean up inactive shell sessions older than 1 day
    $stmt = $conn->prepare("DELETE FROM shell_sessions WHERE is_active = 0 AND last_activity < DATE_SUB(NOW(), INTERVAL 1 DAY)");
    $stmt->execute();
    $deletedSessions = $stmt->affected_rows;
    $stmt->close();
    
    return [
        "commands_deleted" => $deleted,
        "sessions_deleted" => $deletedSessions
    ];
}

// Add error reporting for development (remove in production)
if (defined('DEBUG') && DEBUG) {
    mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
}


?>